Add velocity array support for trajectories scan
dls-controls/pmac pull request #102
Opened 2023-06-07 14:04 UTC by LeandroMartinsdS

This PR is related to the working in progress to remove the velocities calculation from the motion program, and bring it to the driver level.

Some points that still need to be addressed, some of them discussed with @coretl , @ajgdls  and  @JimboMonkey :

- [ ] Fix white spaces to make it clear where are the changes
- [ ] Implement the velocities calculation in the driver level instead of in motion program
  - [ ] Rollback appendVelMode/appendVelArray to append
  - [ ] Substitute VelType for CalcVel, and remove from the broker
  - [ ] Set CalcVel using asyn
  - [ ] Port the equations from the motion program
- [ ] Stop sending the VelMode
- [ ] Update motion programs removing the velocities calculations (and correspondent subprograms)
- [ ] Update the memory buffer
- [ ] Bump motion program version
- [ ] Update tests

If I'm missing something, please let me know.

2023-06-12 15:51 UTC, ajgdls commented
Hi @LeandroMartinsdS I agree with your bullet list of tasks to complete this implementation.

2023-07-05 12:47 UTC, ajgdls commented
Hi @LeandroMartinsdS at the moment it is not possible to download the motion programs to the PMAC.  I think there are a few syntax errors in the pmc files.  I would recommend the following checks:
- Remove any commented lines (I notice a few where there is a "//" but not a ";") to prevent upload errors
- There are still instances of using variables (e.g. Prev_A) but these are no longer defined in the script as they have been commented out.

2023-08-03 10:25 UTC, ajgdls requested changes

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/pmc/trajectory_scan_clipper.pmc
> +#define BuffLen      500    ; Length of buffers
The amount of required memory has increased by close to a factor of two, and this buffer length number has decreased but not by factor of two.  Have you checked this fits within the allowed memory space?

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/pmc/trajectory_scan_code_ppmac.pmc
> +        V_Vel = Next_V_Vel(CalculatedBase)
This needs to map W velocities

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/src/pmacController.cpp
> +  // pBroker_->addReadVariable(pmacMessageBroker::PMAC_SLOW_READ, PMAC_TRAJ_VELOCITY_TYPE);
Added but then left commented out, is this required?

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/src/pmacController.cpp
> +         }
Remove incorrect whitespace

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/src/pmacController.cpp
> +    // TODO:  Add cid check for pppmac
Has this been completed?

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/src/pmacController.cpp
> +
Whitespace

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/src/pmacController.cpp
> +
Remove this commented code if it is not required?

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/unitTests/test_PMACTrajectory.cpp
> +  // BOOST_CHECK_EQUAL(trajectory.getVelocityMode(20, &velocityVal), asynError);
Remove commented code

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/unitTests/test_PMACTrajectory.cpp
> +  // BOOST_CHECK_EQUAL(velocityVal, 5);
Remove commented code

2023-08-03 10:25 UTC, ajgdls commented on pmacApp/unitTests/test_PMACTrajectory.cpp
> +  // BOOST_CHECK_EQUAL(trajectory.append(pos, time, user, velMode, 10), asynError);
Remove commented code

2023-08-03 10:26 UTC, ajgdls commented
Hi @LeandroMartinsdS mostly minor comments, just the velocity mapping that looks incorrect (V and W mixed).

2023-08-03 13:02 UTC, LeandroMartinsdS commented on pmacApp/pmc/trajectory_scan_clipper.pmc
> +#define BuffLen      500    ; Length of buffers
The number of buffers had increased from 10 to 19 by adding the velocities for each axis.
The buffer length has decreased applying the ratio of 10/19, resulting in the buffer length of 500.
By my tests, the buffer fits even for a value close to 530, but supposing that already has some conservative margin I keep the value of 500.

2023-08-07 13:42 UTC, ajgdls commented on pmacApp/pmc/trajectory_scan_clipper.pmc
> +#define BuffLen      500    ; Length of buffers
OK perfect.

2023-08-29 09:44 UTC, LeandroMartinsdS commented
@ajgdls changes are all pushed.

2023-08-29 10:21 UTC, ajgdls approved these changes

2023-09-12 09:02 UTC, merged