Arm ppmac driver fix
dls-controls/pmac pull request #103
Opened 2023-06-16 13:49 UTC by ajgdls

Fix a problem with the PowerPMAC driver that is exposed by the Arm version of the motion controller.  In this version it is possible for messages to arrive without the trailing characters (CR LF) after the command terminator (BELL).  This would mean that the next command echo is prefixed with those characters and corresponding status updates could become out of sync.
The driver has been improved to ensure that these extra characters are checked for and the driver blocks until they are received (or a timeout occurs).  In reality they always arrive within a ms or so.
Some additional debugging log messages have been added.

There are some additional updates planned to improve this driver further, but this is a functional fix for the problem described above.

2023-08-01 10:11 UTC, JimboMonkey requested changes
Hi @ajgdls 

As discussed in our zoom meeting, here are the things which need addressing before a merge.  I'll make separate issues for the other improvements we identified.

1. bytesWritten on line 432 should be a dereferenced pointer
2. The param comments of SSHDriver::read need updating to include the clrf parameter, and correct the typo of bytesWritten instead of bytesRead
3. For SSHDriver::flush, the LIBSSH2_CHANNEL_FLUSH_ALL constant can be used to flush all streams without needing to do them separately
4. Also in the flush function, check the return values of libssh2_channel_flush_ex and libssh2_channel_read separately - flush returns 0 on success and negative on failure; and read returns the number of bytes read or a negative on failure

Thanks,

James

2023-08-01 15:33 UTC, ajgdls commented
Hi @JimboMonkey those changes have been pushed.

2023-08-21 08:25 UTC, LeandroMartinsdS approved these changes
It looks good to me, I have nothing to add.

2023-09-05 14:18 UTC, JimboMonkey approved these changes
Thanks Alan.  Approving the changes and will merge

2023-09-05 14:19 UTC, merged